#!/bin/sh
#
# Chris Mazzullo Apr. 29 2020
#
# Pre-commit runs:
# - non-ascii checker on all changed files
# - isort on all changed .py files
# - flake8 on all changed .py files


CHANGED_FILES=$(git diff --cached --name-only)
if [ ! -z "$CHANGED_FILES" ]
then
    printf "pre-commit: Searching for nonascii characters\n"
    if RESULT=$( grep -THn -P '[^[:ascii:]]' $CHANGED_FILES )
    then
	printf "pre-commit: Non-ascii character(s) found:\n$RESULT\n"
	printf "pre-commit: aborting\n"
	exit 1
    fi
    printf "pre-commit: No non-ascii character(s) found\n"
fi

CHANGED_PY_FILES=$(git diff --cached --name-only | grep '\.py$')
if [ ! -z "$CHANGED_PY_FILES" ]
then
    printf "pre-commit: Running isort on:\n$CHANGED_PY_FILES\n"
    isort $CHANGED_PY_FILES

    printf "pre-commit: Running flake8 on:\n$CHANGED_PY_FILES\n"
    if RESULT=$( flake8 $CHANGED_PY_FILES )
    then
	printf "pre-commit: Files are PEP8 compliant\n"
    else
	printf "pre-commit: PEP8 violations found:\n$RESULT\n\n"
	printf "pre-commit: aborting\n"
	exit 1
    fi
fi

exit 0
